---
title: "Dashboard of New York Weather"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```


```{r p3 data cleaning, include=FALSE}
ny_noaa_cleaned = separate(ny_noaa, date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(tmax = as.integer(tmax)) %>%
  mutate(tmax = tmax/10) %>%
  mutate(tmin = as.integer(tmin)) %>%
  mutate(tmin = tmin/10) %>%
  mutate(prcp = prcp/10) %>%
  sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
```{r}
tmax_jan_july = select(ny_noaa_cleaned, id, year, month, tmax, tmin, prcp) %>%
  filter(month == "01" | month == "07") %>%
  mutate(month = factor(month, labels = c("Jan", "July"))) %>%
  group_by(id, year, month) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE),
            mean_tmin = mean(tmin, na.rm = TRUE),
            mean_prcp = mean(prcp, na.rm = TRUE))
tmax_jan_july %>%
  mutate(text_label = str_c('Year: ', year, ' MaxTemp: ', mean_tmax, ' C')) %>%
  plot_ly(x = ~year, y = ~mean_tmax, type = "scatter", mode = "markers",
          alpha = 0.5,
          color = ~month,
          text = ~text_label)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa_cleaned %>%
  filter(year == 2000 | year == 2001|year == 2002| year == 2003| year == 2004| year == 2005| year == 2006| year == 2007| year == 2008| year == 2009| year == 2010) %>%
  filter(prcp < 10) %>%
  plot_ly(y = ~prcp, color = ~year, type = "box",
          colors = "Set2")
```

-----------------------------------------------------------------------

### Chart C

```{r}
ny_noaa_cleaned %>% 
  count(id) %>% 
  mutate(id = fct_reorder(id, n)) %>% 
  plot_ly(x = ~id, y = ~n, color = ~id, type = "bar")
```

